apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-dotnet-basic-fifdmlat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-dotnet-basic-fifdmlat 
  name: github-tests-dotnet-basic-fifdmlat
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-dotnet-basic-fifdmlat 
